version: '3.1'
services:
  stats-db:
    image: postgres:13.7-alpine
    volumes:
      - /var/lib/postgresql/data/
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=stats
      - POSTGRES_USER=stats
      - POSTGRES_PASSWORD=stats

  stats-server:
    build: stat/stat-server
    ports:
      - "9090:9090"
    depends_on:
      - stats-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/stats
      - SPRING.DATASOURCE.USERNAME=stats
      - SPRING.DATASOURCE.PASSWORD=stats
